@extends('admin.layouts.app')
@section('title', 'Quản lý hỗ trợ IT')
@push('styles')<link rel="stylesheet" href="{{ asset('css/it-support.css') }}?v={{ filemtime(public_path('css/it-support.css')) }}">@endpush
@section('content')
<div class="container-fluid it-page">
    <header class="it-hero"><div><p class="it-eyebrow">QUẢN TRỊ · HỖ TRỢ IT</p><h1>Phiếu yêu cầu hỗ trợ</h1><p>Tiếp nhận, phản hồi và lưu trữ kết quả xử lý cho các chi nhánh.</p></div></header>
    @if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    <nav class="it-tabs" aria-label="Lọc trạng thái phiếu"><a class="{{ !$status ? 'active' : '' }}" href="{{ route('admin.it_support.manage') }}">Tất cả <span>{{ $counts->sum() }}</span></a><a class="{{ $statuses === ['pending','processing'] ? 'active' : '' }}" href="{{ route('admin.it_support.manage', ['status'=>['pending','processing']]) }}">Đang mở <span>{{ ($counts['pending'] ?? 0)+($counts['processing'] ?? 0) }}</span></a><a class="{{ $statuses === ['resolved','closed'] ? 'active' : '' }}" href="{{ route('admin.it_support.manage', ['status'=>['resolved','closed']]) }}">Đã xử lý <span>{{ ($counts['resolved'] ?? 0)+($counts['closed'] ?? 0) }}</span></a>@foreach(['pending'=>'Chờ tiếp nhận','processing'=>'Đang xử lý','resolved'=>'Hoàn thành','closed'=>'Đã đóng'] as $key=>$label)<a class="{{ $status === $key ? 'active' : '' }}" href="{{ route('admin.it_support.manage', ['status'=>$key]) }}">{{ $label }} <span>{{ $counts[$key] ?? 0 }}</span></a>@endforeach</nav>
    <form class="it-filters" action="{{ route('admin.it_support.manage') }}" method="GET">@foreach($statuses as $selectedStatus)<input type="hidden" name="status[]" value="{{ $selectedStatus }}">@endforeach<div><label for="ticketSearch">Tìm phiếu</label><input id="ticketSearch" class="form-control" name="q" value="{{ request('q') }}" placeholder="Mã, tiêu đề, người gửi"></div><div><label for="completedFrom">Hoàn thiện từ</label><input id="completedFrom" class="form-control" type="date" name="completed_from" value="{{ request('completed_from') }}"></div><div><label for="completedTo">Đến ngày</label><input id="completedTo" class="form-control" type="date" name="completed_to" value="{{ request('completed_to') }}"></div><button class="btn it-primary" type="submit"><i class="fas fa-search" aria-hidden="true"></i> Lọc phiếu</button></form>
    <div class="it-list">@forelse($requests as $ticket)<a class="it-ticket" href="{{ route('admin.it_support.show', $ticket) }}"><div class="it-ticket-main"><span class="it-id">PHIẾU #{{ $ticket->id }}</span><h2>{{ $ticket->title }}</h2><p>{{ \Illuminate\Support\Str::limit($ticket->description ?: 'Phiếu cũ chưa có mô tả.', 130) }}</p><div class="it-meta"><span><i class="fas fa-user" aria-hidden="true"></i> {{ $ticket->user?->name ?: 'Người dùng không còn tồn tại' }}</span><span>{{ $ticket->user?->branch?->branch_name ?: 'Chưa có chi nhánh' }}</span><span>Gửi: {{ $ticket->created_at->format('d/m/Y H:i') }}</span>@if($ticket->completed_at)<span>Hoàn thiện: {{ $ticket->completed_at->format('d/m/Y H:i') }}</span>@endif</div></div><div class="it-ticket-end"><span class="it-status it-status--{{ $ticket->status }}">{{ $ticket->statusLabel() }}</span><span class="it-open">Xem và xử lý <i class="fas fa-arrow-right" aria-hidden="true"></i></span></div></a>@empty<div class="it-empty"><i class="far fa-file-alt" aria-hidden="true"></i><h2>Không có phiếu phù hợp</h2><p>Thử chọn trạng thái khác hoặc đổi từ khóa tìm kiếm.</p></div>@endforelse</div>
    <div class="mt-3">{{ $requests->links() }}</div>
</div>
@endsection
