@extends('admin.layouts.app')
@section('title', 'Xử lý phiếu IT #'.$ticket->id)
@push('styles')<link rel="stylesheet" href="{{ asset('css/it-support.css') }}?v={{ filemtime(public_path('css/it-support.css')) }}">@endpush
@section('content')
<div class="container-fluid it-page">
    <header class="it-hero"><div><p class="it-eyebrow">XỬ LÝ PHIẾU #{{ $ticket->id }}</p><h1>{{ $ticket->title }}</h1><p>{{ $ticket->user?->name ?: 'Người gửi không còn tồn tại' }} · {{ $ticket->user?->branch?->branch_name ?: 'Chưa có chi nhánh' }} · {{ $ticket->created_at->format('d/m/Y H:i') }}</p></div><a href="{{ route('admin.it_support.manage') }}" class="btn it-light"><i class="fas fa-arrow-left" aria-hidden="true"></i> Danh sách phiếu</a></header>
    @if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger" role="alert">{{ $errors->first() }}</div>@endif
    <div class="it-detail-layout"><div class="it-detail-main"><section class="it-panel"><div class="it-section-head"><h2>Nội dung yêu cầu</h2><span class="it-status it-status--{{ $ticket->status }}">{{ $ticket->statusLabel() }}</span></div><p class="it-message">{{ $ticket->description ?: 'Phiếu được tạo trước khi chức năng mô tả được bổ sung.' }}</p><div class="it-meta"><span>Phân loại: {{ $ticket->category ?: 'Chưa phân loại' }}</span><span>SĐT: {{ $ticket->contact_phone ?: 'Chưa cung cấp' }}</span></div></section>
        @if(count($ticket->attachmentFiles()))<section class="it-panel"><h2>Tệp đính kèm</h2><div class="it-files">@foreach($ticket->attachmentFiles() as $index=>$file)<a href="{{ route('admin.it_support.download', [$ticket,$index]) }}"><i class="fas fa-paperclip" aria-hidden="true"></i> {{ $file['name'] }} <i class="fas fa-download" aria-hidden="true"></i></a>@endforeach</div></section>@endif
        @if($ticket->resolution_note)<section class="it-panel it-result"><h2>Kết quả xử lý gần nhất</h2><p class="it-message">{{ $ticket->resolution_note }}</p></section>@endif
        <section class="it-panel"><h2>Lịch sử xử lý và trao đổi</h2><div class="it-timeline">@foreach($ticket->events as $event)<div class="it-event"><span class="it-event-dot"></span><div><div class="it-event-head"><strong>{{ $event->actor_name }}</strong><time>{{ $event->created_at?->format('d/m/Y H:i') }}</time></div>@if($event->from_status !== $event->to_status)<small>Trạng thái: {{ ['pending'=>'Chờ tiếp nhận','processing'=>'Đang xử lý','resolved'=>'Đã hoàn thành','closed'=>'Đã đóng'][$event->to_status] ?? $event->to_status }}</small>@endif<p class="it-message">{{ $event->message }}</p></div></div>@endforeach</div></section></div>
        <aside class="it-panel it-workflow"><h2>Phản hồi và cập nhật</h2><p class="it-muted">Mọi thay đổi và phản hồi đều được ghi vào lịch sử phiếu.</p><form action="{{ route('admin.it_support.update_status', $ticket) }}" method="POST">@csrf<label for="status">Trạng thái</label><select class="form-control" id="status" name="status">@foreach(['pending'=>'Chờ tiếp nhận','processing'=>'Đang xử lý','resolved'=>'Đã hoàn thành','closed'=>'Đã đóng'] as $key=>$label)@if(!$ticket->completed_at || in_array($key, ['resolved','closed'], true))<option value="{{ $key }}" @selected(old('status',$ticket->status)===$key)>{{ $label }}</option>@endif @endforeach</select><label for="message" class="mt-3">Phản hồi / kết quả xử lý</label><textarea class="form-control" id="message" name="message" rows="6" maxlength="3000" placeholder="Nêu hướng xử lý hoặc kết quả để người gửi nắm rõ...">{{ old('message') }}</textarea><small class="form-text text-muted">Cần ghi kết quả khi hoàn thành hoặc đóng phiếu.</small><button type="submit" class="btn it-primary it-submit">Lưu cập nhật</button></form><div class="it-archive-info"><strong>Lưu trữ</strong><p>Ngày hoàn thiện: {{ $ticket->completed_at?->format('d/m/Y H:i') ?: 'Chưa hoàn thiện' }}</p><small>Tệp và bản ghi phiếu được xếp theo năm / tháng / ngày hoàn thiện trong kho riêng.</small></div></aside></div>
</div>
@endsection
