@extends('user.layouts.app')
@section('title', 'Phiếu hỗ trợ #'.$ticket->id)
@push('styles')<link rel="stylesheet" href="{{ asset('css/it-support.css') }}?v={{ filemtime(public_path('css/it-support.css')) }}">@endpush
@section('content')
<div class="container-fluid it-page">
    <header class="it-hero"><div><p class="it-eyebrow">PHIẾU #{{ $ticket->id }}</p><h1>{{ $ticket->title }}</h1><p>Gửi lúc {{ $ticket->created_at->format('d/m/Y H:i') }} · @if($ticket->category){{ $ticket->category }} · @endif<span class="it-status it-status--{{ $ticket->status }}">{{ $ticket->statusLabel() }}</span></p></div><a href="{{ route('user.it_support.index') }}" class="btn it-light"><i class="fas fa-arrow-left" aria-hidden="true"></i> Danh sách phiếu</a></header>
    @if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger" role="alert">{{ $errors->first() }}</div>@endif
    <div class="it-detail-layout"><div class="it-detail-main"><section class="it-panel"><h2>Nội dung yêu cầu</h2><p class="it-message">{{ $ticket->description ?: 'Phiếu được tạo trước khi chức năng mô tả được bổ sung.' }}</p><div class="it-meta"><span>Liên hệ: {{ $ticket->contact_phone ?: 'Chưa cung cấp' }}</span>@if($ticket->completed_at)<span>Ngày lưu trữ: {{ $ticket->completed_at->format('d/m/Y H:i') }}</span>@endif</div></section>
        @if(count($ticket->attachmentFiles()))<section class="it-panel"><h2>Tệp đính kèm</h2><div class="it-files">@foreach($ticket->attachmentFiles() as $index => $file)<a href="{{ route('user.it_support.download', [$ticket, $index]) }}"><i class="fas fa-paperclip" aria-hidden="true"></i> {{ $file['name'] }} <i class="fas fa-download" aria-hidden="true"></i></a>@endforeach</div></section>@endif
        @if($ticket->resolution_note)<section class="it-panel it-result"><h2><i class="fas fa-check-circle" aria-hidden="true"></i> Kết quả xử lý</h2><p class="it-message">{{ $ticket->resolution_note }}</p></section>@endif
        <section class="it-panel"><h2>Trao đổi và lịch sử xử lý</h2><div class="it-timeline">@foreach($ticket->events as $event)<div class="it-event"><span class="it-event-dot"></span><div><div class="it-event-head"><strong>{{ $event->actor_name }}</strong><time>{{ $event->created_at?->format('d/m/Y H:i') }}</time></div>@if($event->from_status !== $event->to_status)<small>Cập nhật trạng thái: {{ ['pending'=>'Chờ tiếp nhận','processing'=>'Đang xử lý','resolved'=>'Đã hoàn thành','closed'=>'Đã đóng'][$event->to_status] ?? $event->to_status }}</small>@endif<p class="it-message">{{ $event->message }}</p></div></div>@endforeach</div>
            @if($ticket->status !== 'closed')<form action="{{ route('user.it_support.reply', $ticket) }}" method="POST" class="it-reply">@csrf<label for="message">Bổ sung thông tin / phản hồi</label><textarea class="form-control" id="message" name="message" rows="3" minlength="3" maxlength="3000" required placeholder="Gửi thêm chi tiết cho IT...">{{ old('message') }}</textarea><button class="btn it-primary" type="submit">Gửi phản hồi</button></form>@endif
        </section></div><aside class="it-panel it-help"><h2>Thông tin lưu trữ</h2><p><strong>Mã phiếu:</strong> #{{ $ticket->id }}</p><p><strong>Ngày gửi:</strong> {{ $ticket->created_at->format('d/m/Y H:i') }}</p><p><strong>Trạng thái:</strong> {{ $ticket->statusLabel() }}</p><p><strong>Ngày hoàn thiện:</strong> {{ $ticket->completed_at?->format('d/m/Y H:i') ?: 'Chưa hoàn thiện' }}</p><small>Phiếu hoàn thiện được lưu theo năm / tháng / ngày để đối chiếu về sau.</small></aside></div>
</div>
@endsection
